{"name": "Test - Validar la creación de un Beneficiario", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=45125): Max retries exceeded with url: /session/1e12bbba4badd8917a80a45c78b6d8eb/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a1952ec2040>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 56, in after_step\n    pm.hook.after_step(context=context, step=step)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ipadula/Avla/helper/plugins/SeleniumPlugin.py\", line 187, in after_step\n    allure.attach(context.browser.get_screenshot_as_png(), name=\"screenshot\", attachment_type=AttachmentType.PNG)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 785, in urlopen\n    retries = retries.increment(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given Estoy en el ingreso al portal sin loguearme", "status": "passed", "attachments": [{"name": "screenshot", "source": "8654ae30-3ccf-49b9-a31e-9e2e31d73901-attachment.png", "type": "image/png"}], "start": 1751635810794, "stop": 1751635815533}, {"name": "When Me logueo con las credenciales \"admin\"", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=45125): Max retries exceeded with url: /session/1e12bbba4badd8917a80a45c78b6d8eb/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a1952ec2040>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 56, in after_step\n    pm.hook.after_step(context=context, step=step)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ipadula/Avla/helper/plugins/SeleniumPlugin.py\", line 187, in after_step\n    allure.attach(context.browser.get_screenshot_as_png(), name=\"screenshot\", attachment_type=AttachmentType.PNG)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 785, in urlopen\n    retries = retries.increment(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1751635815533, "stop": 1751635818770}, {"name": "And Despliego la seccion \"Manutenção\"", "status": "skipped", "start": 1751635818784, "stop": 1751635818784}, {"name": "And Me dirijo a la seccion \"Congenêres\"", "status": "skipped", "start": 1751635818784, "stop": 1751635818784}, {"name": "And Presiono el boton \"Novo\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Selecciono en \"ID Type\" \"SSN\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Selecciono en \"Legal Person Type\" \"Individual\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Agrego un \"ID Number\" \"a\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Agrego un \"Name\" \"a\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Selecciono en \"Company Type\" \"Public\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Selecciono \"Physical\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Agrego un \"Address Number\" \"a\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Agrego un \"Street Name\" \"a\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Agrego un \"Street Name 2\" \"a\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Agrego un \"ZIP Code\" \"a\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Selecciono en \"State\" \"Arkansas\" en \"General data\"", "status": "skipped", "start": 1751635818785, "stop": 1751635818785}, {"name": "And Selecciono en \"City\" \"ALLEENE\" en \"General data\"", "status": "skipped", "start": 1751635818786, "stop": 1751635818786}, {"name": "And Presiono \"Add\"", "status": "skipped", "start": 1751635818786, "stop": 1751635818786}, {"name": "And Presiono \"Save\"", "status": "skipped", "start": 1751635818786, "stop": 1751635818786}, {"name": "And Presiono \"Yes\"", "status": "skipped", "start": 1751635818786, "stop": 1751635818786}, {"name": "And Me dirijo a la seccion \"Congenêres\"", "status": "skipped", "start": 1751635818786, "stop": 1751635818786}, {"name": "And Selecciono \"SSN\"", "status": "skipped", "start": 1751635818786, "stop": 1751635818786}, {"name": "And Agrego un \"ID Number\"", "status": "skipped", "start": 1751635818786, "stop": 1751635818786}, {"name": "And Presiono el boton para buscar", "status": "skipped", "start": 1751635818786, "stop": 1751635818786}, {"name": "Then Valido que exista un resultado", "status": "skipped", "start": 1751635818786, "stop": 1751635818786}], "start": 1751635809064, "stop": 1751635818786, "uuid": "8954f611-d4da-4030-804f-22db9e7fa156", "historyId": "0ea1fd59225e32d7b5f6031f05805db6", "fullName": "Manutenção: Test - Validar la creación de un Beneficiario", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "mantenimiento"}, {"name": "tag", "value": "obligees"}, {"name": "tag", "value": "regresion"}, {"name": "feature", "value": "Manutenção"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}